# Generated by Django 4.2.7 on 2024-02-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answerText',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='rate',
            new_name='down_vote',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='isRead',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='isAnonymous',
            new_name='is_anonymous',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='isAnswered',
            new_name='is_answered',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='questionText',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='downVotedProfiles',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='upVotedProfiles',
        ),
        migrations.RemoveField(
            model_name='skillrate',
            name='rate',
        ),
        migrations.AddField(
            model_name='answers',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
