# Generated by Django 4.2.7 on 2024-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_answertext_answers_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='down_vote',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='up_vote',
        ),
        migrations.AddField(
            model_name='answers',
            name='down_vote',
            field=models.ManyToManyField(related_name='answers_voted_down', to='core.profile'),
        ),
        migrations.AddField(
            model_name='answers',
            name='up_vote',
            field=models.ManyToManyField(related_name='answers_voted_up', to='core.profile'),
        ),
    ]
